apiVersion: v2
name: image-preheat
description: Kubernetes DaemonSet 镜像预热与节点间分发系统
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - image
  - preheat
  - kubernetes
  - daemonset
  - docker
home: https://github.com/your-org/image-preheat
sources:
  - https://github.com/your-org/image-preheat
maintainers:
  - name: Your Name
    email: your.email@example.com 