# Default values for image-preheat
# This is a YAML-formatted file.

# 全局配置
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

# 镜像配置
image:
  repository: your-registry/image-preheat
  tag: "latest"
  pullPolicy: IfNotPresent

# 镜像拉取密钥
imagePullSecrets: []
# 镜像列表配置
imageList:
  - "nginx:latest"
  - "redis:7-alpine"
  - "postgres:15"

# 应用配置
config:
  # 分布式锁配置
  lockConfigMap: "image-preheat-lock"
  lockTimeout: "5m"
  
  # 镜像列表配置
  imageListPath: "/etc/preheater/images.list"
  
  # 并发控制
  preheatConcurrency: 1
  downloadAPIConcurrency: 4
  
  # 时间配置
  interval: "1m"
  pullingTimeout: "5m"
  peerDiscoveryInterval: "30s"
  
  # 目录配置
  mountDir: "/etc/preheater"
  
  # 限速配置（字节/秒）
  downloadRateLimit: "524288000"  # 500MB/s

# 资源限制
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

# 标签
labels: {}
# 注解
annotations: {} 
# 节点选择器
nodeSelector: {}

# 容忍度
tolerations: []

# 亲和性
affinity: {}